import {
  baseusproduct,
  infinixproduct,
  itelproduct,
  linkoproduct,
  newageproduct,
  oraimoproduct,
  pooleeproduct,
  rexiproduct,
  romossproduct,
} from "./powerbankgen";

export const powerbankproducts = [
  {
    id: 1,
    name: "Baseus 20,000mAh 65W Power Bank",
    image: baseusproduct.baseus1,
    images: [
      baseusproduct.baseus1,
      baseusproduct.baseus2,
      baseusproduct.baseus3,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "65W Power Delivery fast charging",
      "20,000mAh high-capacity battery",
      "Charge up to 5 devices simultaneously",
      "Digital display for battery level",
      "Dual USB + USB-C ports",
      "Fast recharge (≈2.5 hours with 60W charger)",
      "Compatible with phones, tablets & laptops",
      "Sleek and portable design",
    ],
  },

  {
    id: 2,
    name: "Infinix 10000mAH Power Bank USB C In/out Xpower10",
    image: infinixproduct.infinix1,
    images: [
      infinixproduct.infinix1,
      infinixproduct.infinix1b,
      infinixproduct.infinix1c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Capacity - 10,000mah",
      "Power rated input 12W",
      "Power output 12W",
      "USB output port - 2usb 1 typeC",
      "TypeC support - dual",
      "Infinix Xpower10",
      "Compatible with phones & tablets",
      "Sleek and portable design",
    ],
  },

  {
    id: 3,
    name: "Infinix 20000mAH Power Bank USB C In/out Xpower20 Go",
    image: infinixproduct.infinix2,
    images: [
      infinixproduct.infinix2,
      infinixproduct.infinix2b,
      infinixproduct.infinix2c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20000mAh Capacity - Charge multiple devices several times",
      "Fast Charging - Quick, efficient power for phones and tablets",
      "Dual USB + Type-C Ports - Charge two devices at the same time",
      "Compact & Portable - Easy to carry for travel or daily use",
      "Dual USB + USB-C ports",
      "Smart Safety Features - Protects devices from overcharge, overheat, and short circuits",
      "Compatible with phones & tablets",
      "Sleek and portable design",
    ],
  },

  {
    id: 4,
    name: "Infinix Gt Power 20000mAh 55W Portable Laptop Charging Powerbank",
    image: infinixproduct.infinix3,
    images: [
      infinixproduct.infinix3,
      infinixproduct.infinix3b,
      infinixproduct.infinix3c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    description: "",
    features: [
      "1 year warranty",
      "55W Super Fast Laptop Charging Speed",
      "Attached type C braided cable (55W)",
      "Attached cable also act as lanyard",
      "Type C out port (In and Out)",
      "20000mAh capacity",
      "Compatible with phones & tablets",
      "Digital power display",
    ],
  },

  {
    id: 5,
    name: "itel 40000mAh 22.5W Fast Charging Type-C Output Powerbank",
    image: itelproduct.itel1,
    images: [itelproduct.itel1, itelproduct.itel1b, itelproduct.itel1c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "40,000mAh Large Capacity",
      "22.5 Watts Fast Charging",
      "4 x  USB Output, 2 x Type-C Input and Output",
      "Up to 22.5W Fast Charging for 6 devices",
      "Bright Torch",
      "12 Months Warranty by Carlcare",
      "Up to 6 times Phone Charging",
      "Type-C Input and Output",
      "Anti-Slip Texture",
      "Certified Safe: 10 Security Protection",
    ],
  },

  {
    id: 6,
    name: "itel 27000mAh 65W Type-C Phone & Laptop Power Bank With Torch",
    image: itelproduct.itel2,
    images: [itelproduct.itel2, itelproduct.itel2b, itelproduct.itel2c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Power LAPTOPS & TABLETS with Type-C Port",
      "65W Fast Charging Type-C In & Out",
      "Flight Friendly",
      "27,000mAh Massive Capacity",
      "Charge up to 4 devices at once",
      "Four Ports (3 USB-A, 1 Type-C In & Out)",
      "Up to 7x Charges",
      "Output Type-C:  5V 3A, 9V 3A, 12V 3A, 15V 3A, 20V 3.25A (65W Max)",
      "Input Type-C:  5V 3A, 9V 3A, 12V 3A, 15V 3A, 20V 3.25A (65W Max) ",
      "Universal Compatibility27,000mAh Large Capacity",
    ],
  },

  {
    id: 7,
    name: "Itel 27000mAh 22.5W Fast Charging Power Bank + Free 18W Charger",
    image: itelproduct.itel3,
    images: [itelproduct.itel3, itelproduct.itel3b, itelproduct.itel3c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "27,000mAh Large Capacity",
      "Free 18 Watts Fast Charger",
      "22.5 Watts Fast Charging",
      "Bright Torch",
      "3 x  USB Output, 1 x Type-C Output",
      "Up to 22.5W Fast Charging for Four",
      "Up to 4.5 times Phone Charging",
      "Type-C Input and Output",
      "Anti-Slip Texture",
      "Certified Safe: 10 Security Protection",
      "super fast",
    ],
  },

  {
    id: 8,
    name: "itel 20000mAh 15W Fast Charging Type-C Output Star200P Power Bank",
    image: itelproduct.itel4,
    images: [itelproduct.itel4, itelproduct.itel4b, itelproduct.itel4c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20,000mAh Strong Capacity",
      "15Watts Fast Charging",
      "Digital Display",
      "Micro USB & Type-C Dual Input",
      "Up to 3A Fast Charging for up to 3 Devices",
      "12 Months Warranty by Carlcare",
      "Anti-Slip Texture",
      "Certified Safe: Itel Superior Safety",
    ],
  },

  {
    id: 9,
    name: "Itel 27000mAh 22.5W Fast Charging Power Bank + Free 18W Charger",
    image: itelproduct.itel5,
    images: [itelproduct.itel5, itelproduct.itel5b, itelproduct.itel5c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "27,000mAh Large Capacity",
      "Free 18 Watts Fast Charger",
      "22.5 Watts Fast Charging",
      "Bright Torch",
      "3 x  USB Output, 1 x Type-C Output",
      "Up to 22.5W Fast Charging for Four",
      "Up to 4.5 times Phone Charging",
      "Type-C Input and Output",
      "Anti-Slip Texture",
      "Certified Safe: 10 Security Protection",
      "super fast",
    ],
  },

  {
    id: 10,
    name: "LINKCO 50000 mAh Fast Charging Powerbank 22.5W With Bright Torch",
    image: linkoproduct.linko1,
    images: [linkoproduct.linko1, linkoproduct.linko1b, linkoproduct.linko1c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "50,000mAh Large Capacity",
      "Up to 22.5W Fast Charging for Four",
      "3 x  USB Output, 1 x Type-C Output",
      "Dual Input: 1 x Type-C, 1 x Micro USB",
      "With Bright Torch",
      "12 Months Warranty",
      "Up to 10 times Phone Charging",
      "Type-C Input and Output",
      "Certified Safe: Security Protection",
    ],
  },

  {
    id: 11,
    name: "LINKCO 30000mAh Powerbank With 22.5W Fast Charging Powerbank",
    image: linkoproduct.linko2,
    images: [linkoproduct.linko2, linkoproduct.linko2b, linkoproduct.linko2c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "30,000mAh Large Capacity",
      "22.5 Watts Fast Charging",
      "2 x  USB Output, 1 x Type-C Output",
      "Up to 22.5W Fast Charging for Four",
      "With Bright Torch",
      "12 Months Warranty",
      "Up to 4.5 times Phone Charging",
      "Type-C Input and Output",
      "Certified Safe: Security Protection",
    ],
  },

  {
    id: 12,
    name: "LINKCO 20000mAh Portable Power Bank – Fast Charging Dual USB & Type-C With LED Torch",
    image: linkoproduct.linko3,
    images: [linkoproduct.linko3, linkoproduct.linko3b, linkoproduct.linko3c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    description: "",
    features: [
      " 20000mAh high-capacity battery",
      "Fast charging support up to 3A output",
      "Dual USB output ports for charging two devices",
      "Type-C input/output for faster charging",
      "Built-in LED torchlight",
      "Multiple protection system for safe charging",
      "Compact and portable design",
      "Compatible with smartphones, tablets, and USB devices",
    ],
  },

  {
    id: 13,
    name: "New Age RH018 80000mAhh 130W Fast Laptop Power-Bank Heavy-Duty AI With Type-C In-put And Out-put",
    image: newageproduct.newage1,
    images: [
      newageproduct.newage1,
      newageproduct.newage1b,
      newageproduct.newage1c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "130W High-Power Output: Efficiently charges phones, tablets, laptops, cameras, and small devices.",
      "Multiple Charging Ports: Includes USB-C PD, dual USB-A fast charge, and AC/DC outputs.",
      "Compact & Lightweight: Weighs only 1.8 kg for easy carrying anywhere.",
      "Smart Battery Protection: Built-in overcharge, short circuit, and temperature control systems.",
      "Integrated LED Flashlight: Bright illumination for camping or emergencies.",
      "Ergonomic Design: Sleek finish with a sturdy red handle and foldable cover for port protection.",
      "Rechargeable & Eco-Friendly: Uses high-efficiency lithium-ion cells for long-lasting power",
      "Certified Safe: 10 Security Protection",
    ],
  },

  {
    id: 14,
    name: "Turbo Ultra 5 – 55000mAh Power Bank (With Torch Light)",
    image: newageproduct.newage2,
    images: [
      newageproduct.newage2,
      newageproduct.newage2b,
      newageproduct.newage2c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Charge your smartphone 10–15 times or a tablet 4–6 times on a single charge—ideal for long trips and power outages.",
      "Multiple USB ports allow you to charge several devices at once—from phones and tablets to Bluetooth gadgets.",
      "The integrated LED flashlight provides bright and reliable light for camping, emergencies, and nighttime use.",
      "Delivers quick, efficient charging to compatible devices—saves time and keeps you moving.",
      "Equipped with overcharge, short-circuit, and temperature protection for safe, worry-free charging.",
      "Rugged design made for travel and outdoor use, with an ergonomic grip and compact form factor.",
      "The LED display shows real-time battery levels, so you're never caught off guard.",
    ],
  },

  {
    id: 15,
    name: "New Age Turbo 2 – 33,000mAh Power Bank (With Torch Light)",
    image: newageproduct.newage3,
    images: [
      newageproduct.newage3,
      newageproduct.newage3b,
      newageproduct.newage3c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "33000mAh large capacity (charges phones multiple times)",
      "Fast charging support (up to 3A output)",
      "Multiple ports – 2 USB + 1 Type-C",
      "Type-C two-way charging (input & output)",
      "LED display for battery level",
      "Built-in torch light",
      "Safety protection (overcharge, short circuit, overheating)",
      "Can power devices for days (up to ~2 weeks use)",
    ],
  },

  {
    id: 16,
    name: "New Age Turbo Ultra 11 33000mAh 20W PD Fast Charging Type-C Input & Output Digital Display Power-Bank",
    image: newageproduct.newage4,
    images: [
      newageproduct.newage4,
      newageproduct.newage4b,
      newageproduct.newage4c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "30000mAh high capacity (long-lasting power)",
      "20W fast charging (PD support)",
      "Multiple ports (USB + Type-C)",
      "Type-C input & output (two-way charging)",
      "Digital LED display (battery percentage)",
      "Built-in torch light (useful at night)",
      "Smart protection system (overcharge, overheating, short circuit)",
    ],
  },

  {
    id: 17,
    name: "J175L-20k 22500mAh Power Bank (With In-built Cables)",
    image: newageproduct.newage5,
    images: [
      newageproduct.newage5,
      newageproduct.newage5b,
      newageproduct.newage5c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "22500mAh high capacity (charges phones multiple times)",
      "20W fast charging (PD support)",
      "Dual ports (USB + Type-C)",
      "Type-C two-way charging (input & output)",
      "LED indicator/display (battery level)",
      "Charge 2 devices at once",
      "Multi-protection safety system (overcharge, heat, short circuit)",
      "Portable & travel-friendly design",
    ],
  },

  {
    id: 18,
    name: "New Age 22500 Power Bank With Type-C Port Input & Output",
    image: newageproduct.newage6,
    images: [
      newageproduct.newage6,
      newageproduct.newage6b,
      newageproduct.newage6c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "22500mAh large capacity (charges phones 4–6 times)",
      "Fast charging (up to ~20W / 22.5W)",
      "Multiple ports (USB + Type-C)",
      "Type-C two-way charging (input & output)",
      "LED display (battery percentage)",
      "Built-in torch light (on some models)",
      "Charge 2 devices at once",
      "Safety protection (overcharge, heat, short circuit)",
    ],
  },

  {
    id: 19,
    name: "New Age 22500mAh Turbo Ultra 8 Fast Charging Digital Display Type-C Input and Output Power Bank",
    image: newageproduct.newage7,
    images: [
      newageproduct.newage7,
      newageproduct.newage7b,
      newageproduct.newage7c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "22500mAh large capacity (charges phones multiple times)",
      "Fast charging (up to 3A output)",
      "Multiple ports – 2 USB + Type-C",
      "Type-C two-way charging (input & output)",
      "LED display (battery percentage)",
      "4-layer safety protection (overcharge, heat, short circuit)",
      "Charge multiple devices at once",
      "Portable & durable design",
    ],
  },

  {
    id: 20,
    name: "New Age SUPER MAGNETIC 10000mAh J172-10K Mag-Safe Wireless 20W Fast Charging Power-Bank (NEW MODEL)",
    image: newageproduct.newage8,
    images: [
      newageproduct.newage8,
      newageproduct.newage8b,
      newageproduct.newage8c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "10000mAh capacity (2–3 full charges)",
      "Wireless charging (Qi enabled)",
      "22.5 Watts Fast Charging",
      "Bright Torch",
      "3 x  USB Output, 1 x Type-C Output",
      "Up to 22.5W Fast Charging for Four",
      "Up to 4.5 times Phone Charging",
      "Type-C Input and Output",
      "Anti-Slip Texture",
      "Certified Safe: 10 Security Protection",
      "super fast",
    ],
  },

  {
    id: 21,
    name: "Oraimo PowerJet 130 27600mAh 130W Power Bank",
    image: oraimoproduct.oraimo1,
    images: [
      oraimoproduct.oraimo1,
      oraimoproduct.oraimo1b,
      oraimoproduct.oraimo1c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "27600mAh massive capacity (can charge laptop ~2 times)",
      "130W super fast charging (powers laptops + phones)",
      "Laptop support (up to 100W Type-C output)",
      "3 output ports - 2 Type-C + 1 USB-A (charge 3 devices)",
      "100W fast recharge (full charge in ~1.5 hours)",
      "Smart LED display (battery & charging status)",
      "Wide compatibility (MacBook, HP, Dell, phones, tablets)",
      "Advanced safety protection system",
    ],
  },

  {
    id: 22,
    name: "Oraimo 10000mAh Ultra Slim Fast Charging Toast Power Bank",
    image: oraimoproduct.oraimo2,
    images: [
      oraimoproduct.oraimo2,
      oraimoproduct.oraimo2b,
      oraimoproduct.oraimo2c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "10000mAh capacity (about 2–3 phone charges)",
      "Fast charging (15W–22.5W depending on model)",
      "Multiple ports – USB + Type-C (charge 2–3 devices)",
      "Type-C two-way charging (input & output)",
      "Smart fast-charge tech (AniFast™) for efficient charging",
      "Slim & lightweight design (easy to carry)",
      "Multi-layer safety protection system",
    ],
  },

  {
    id: 23,
    name: "POOLEE 50000mah powerbank -FAST CHARGING",
    image: pooleeproduct.poolee1,
    images: [
      pooleeproduct.poolee1,
      pooleeproduct.poolee1b,
      pooleeproduct.poolee1c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "50000mAh massive capacity (charges phones 5-10+ times)",
      "22.5W fast charging (PD support)",
      "Multiple ports (up to 4 USB + Type-C)",
      "Type-C input & output (two-way charging)",
      "Charge multiple devices at once (up to 4-6 devices)",
      "Built-in torch light",
      "Built-in cables (on some models)",
      "Safety protection system (overcharge, heat, short circuit)",
    ],
  },

  {
    id: 24,
    name: "POOLEE 30000 Power Bank Flash Type-C Fast Charging",
    image: pooleeproduct.poolee2,
    images: [
      pooleeproduct.poolee2,
      pooleeproduct.poolee2b,
      pooleeproduct.poolee2c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "30000mAh large capacity (charges phones 4–7 times)",
      "Fast charging (up to ~2.1A / 22.5W on some models)",
      "Multiple ports (USB + Type-C, some with dual outputs)",
      "Type-C input & output (two-way charging)",
      "Digital LED display (battery level)",
      "Charge multiple devices at once",
      "Safety protection system (overcharge, short circuit)",
      "Durable, anti-slip design",
    ],
  },

  {
    id: 25,
    name: "Poolee 22000MAH Power Bank Titan Type-C In/out Fast Charging",
    image: pooleeproduct.poolee3,
    images: [
      pooleeproduct.poolee3,
      pooleeproduct.poolee3b,
      pooleeproduct.poolee3c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "22000mAh high capacity (charges phones about 4-5 times)",
      "Fast charging (up to 2.4A output)",
      "Dual USB ports (charge 2 devices at once)",
      "Type-C + Micro USB input (flexible charging options)",
      "Lithium polymer battery (safer & more durable)",
      "LED/analogue battery indicator",
      "Multi-protection system (overcharge, heat, short circuit)",
      "Portable & compact design",
    ],
  },

  {
    id: 26,
    name: "POOLEE 20000mAh Flash Power Bank Type-C Fast Charging",
    image: pooleeproduct.poolee4,
    images: [
      pooleeproduct.poolee4,
      pooleeproduct.poolee4b,
      pooleeproduct.poolee4c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20000mAh capacity (charges phones 3-5 times)",
      "Fast charging (up to 22.5W on some models)",
      "Dual USB + Type-C ports (charge multiple devices)",
      "Type-C input & output (two-way charging)",
      "Built-in torch light",
      "LED indicator/display (battery level)",
      "Multi-protection safety system (overcharge, heat, short circuit)",
      "Compact & portable design",
    ],
  },

  {
    id: 27,
    name: "POOLEE 20000 mAh Power Bank LED Display Battery",
    image: pooleeproduct.poolee5,
    images: [
      pooleeproduct.poolee5,
      pooleeproduct.poolee5b,
      pooleeproduct.poolee5c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20000mAh capacity (charges phones 3–5 times)",
      "Fast charging support (efficient power output)",
      "Dual USB + Type-C ports (charge multiple devices)",
      "Type-C input & output (two-way charging)",
      "LED torch light (useful in darkness / outages)",
      "LED display/indicator (battery level)",
      "Multi-protection safety system (overcharge, heat, short circuit)",
      "Compact & portable design",
    ],
  },

  {
    id: 28,
    name: "RMB30-T 30000mAh Built-in Cable",
    image: rexiproduct.rexi1,
    images: [rexiproduct.rexi1, rexiproduct.rexi1b, rexiproduct.rexi1c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "30000mAh large capacity (charges phones many times)",
      "Fast charging support (up to ~22.5W on some models)",
      "Multiple ports (USB-A + Type-C, some with 3–4 outputs)",
      "Dual input & output (Charge multiple devices + recharge power bank)",
      "LED digital display (battery percentage)",
      "Built-in flashlight/LED light (on some variants)",
      "Safety protections (overcharge, overheat & short circuit)",
      "Portable & handy design for travel/outdoor use",
    ],
  },

  {
    id: 29,
    name: "Oraimo Traveler 15 15w Fast Charging Type-C Power Bank ",
    image: rexiproduct.rexi2,
    images: [rexiproduct.rexi2, rexiproduct.rexi2b, rexiproduct.rexi2c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20000mAh capacity — multiple phone charges",
      "Fast charging support (up to ~22.5W on some models)",
      "Dual ports (USB-A + Type-C) — charge 2 devices at once",
      "Type-C two-way charging (input & output)",
      "LED battery level display",
      "Safety protections (over-charge, over-heat, short-circuit)",
      "Portable & travel-friendly design",
    ],
  },

  {
    id: 30,
    name: "Romoss 60000mAh Powerful 100W Fast Charge Battery Laptop Power Bank",
    image: romossproduct.romoss1,
    images: [
      romossproduct.romoss1,
      romossproduct.romoss1b,
      romossproduct.romoss1c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "60000mAh ultra-massive capacity (up to 10–12 phone charges, laptops 2–3 times)",
      "100W super fast charging (PD) – powers laptops & heavy devices",
      "Laptop support via USB-C (MacBook, Dell, HP, etc.)",
      "Multiple ports – 2 USB-C + 2 USB-A (charge many devices at once)",
      "Fast recharge (up to 100W input) (~4–5 hours full charge)",
      "Smart LED display (battery %, voltage, status)",
      "Built-in flashlight (on some models)",
      "Advanced safety protection system (overcharge, heat, short circuit)",
    ],
  },

  {
    id: 31,
    name: "Romoss 60000mA Powerful 22.5W Fast Charge Battery Power Bank",
    image: romossproduct.romoss2,
    images: [
      romossproduct.romoss2,
      romossproduct.romoss2b,
      romossproduct.romoss2c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "60000mAh ultra-massive capacity (can last days / weeks of use)",
      "Fast charging (22.5W SCP + 18W PD/QC 3.0)",
      "4 output ports (charge up to 4 devices at once)",
      "3 input ports (Type-C, Micro USB, Lightning)",
      "Smart LED display (battery %, voltage, status)",
      "Built-in flashlight (useful for outages)",
      "Advanced safety protection system",
      "Can charge phones 10–20+ times",
    ],
  },

  {
    id: 32,
    name: "Romoss 40000mAh Fast Charging 22.5W Power Bank",
    image: romossproduct.romoss3,
    images: [
      romossproduct.romoss3,
      romossproduct.romoss3b,
      romossproduct.romoss3c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "40000mAh massive capacity (charges phones 6–10+ times)",
      "22.5W fast charging (PD + QC 3.0 support)",
      "Multiple output ports (charge 2–3 devices at once)",
      "Two-way fast charging (Type-C input & output)",
      "Smart LED/LCD display (battery %, voltage, current)",
      "Long-lasting backup (great for travel & power outages",
      "Multi-protection safety system (overcharge, heat, short circuit)",
      "Durable but slightly heavy design (high capacity build)",
    ],
  },

  {
    id: 33,
    name: "Romoss PEA 40 PRO 65watts power bank",
    image: romossproduct.romoss4,
    images: [
      romossproduct.romoss4,
      romossproduct.romoss4b,
      romossproduct.romoss4c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "40000mAh massive capacity (phones 6–9 times, laptop ~2 times)",
      "65W fast charging (PD + QC support) – works for laptops & phones)",
      "Laptop support via USB-C (MacBook, Dell, HP, etc.)",
      "Multiple ports (USB-A + USB-C, up to 3 devices at once)",
      "Multiple input options (Type-C, Micro USB, Lightning on some models)",
      "Smart LED display (battery %, voltage, current)",
      "Super fast recharge (~6 hours)",
      "Advanced safety protection system",
    ],
  },

  {
    id: 34,
    name: "Romoss 30000mAh Digital Fast Charger LED Display Powerbank",
    image: romossproduct.romoss5,
    images: [
      romossproduct.romoss5,
      romossproduct.romoss5b,
      romossproduct.romoss5c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "30000mAh large capacity (charges phones ~5–7 times)",
      "22.5W fast charging (PD + QC 3.0)",
      "3 output ports (2 USB-A + 1 Type-C) – charge multiple devices",
      "3 input ports (Type-C, Micro USB, Lightning)",
      "LED digital display (battery %, voltage, status)",
      "Charge up to 3 devices at once",
      "Advanced safety protection (overcharge, heat, short circuit)",
      "Long-lasting backup (great for travel & outages)",
    ],
  },

  {
    id: 35,
    name: "Romoss 30000mAh Power Bank 22.5W Fast Charge(3 Inputs/3 Outputs)",
    image: romossproduct.romoss6,
    images: [
      romossproduct.romoss6,
      romossproduct.romoss6b,
      romossproduct.romoss6c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "30000mAh large capacity (charges phones 5–7+ times)",
      "22.5W fast charging (PD + QC support)",
      "3 output ports (charge up to 3 devices at once)",
      "3 input ports (Type-C, Micro USB, Lightning)",
      "LED digital display (battery %, status)",
      "Fast recharge (~8 hours with PD charger)",
      "Wide compatibility (phones, tablets, earbuds, etc.)",
      "Smart safety protection system (overcharge, heat, short circuit)",
    ],
  },

  {
    id: 36,
    name: "Romoss Sense 8 Power Banks 30000mAh Fast Charging",
    image: romossproduct.romoss7,
    images: [
      romossproduct.romoss7,
      romossproduct.romoss7b,
      romossproduct.romoss7c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "30000mAh large capacity (charges phones 5–7+ times)",
      "18W fast charging (PD + QC support)",
      "3 output ports (2 USB + 1 Type-C) – charge 3 devices at once",
      "3 input ports (Type-C, Micro USB, Lightning)",
      "LED indicator lights (battery level display)",
      "Two-way fast charging (charge devices + recharge power bank fast)",
      "10-layer safety protection system",
      "Travel-friendly & durable design",
    ],
  },

  {
    id: 37,
    name: "Romoss SW30PF 30000mAh PD QC 3.0 Quick Charge Powerbank",
    image: romossproduct.romoss8,
    images: [
      romossproduct.romoss8,
      romossproduct.romoss8b,
      romossproduct.romoss8c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "30000mAh large capacity (charges phones 5–7+ times)",
      "Fast charging (up to 22.5W / 33W PD) – quick power for phones & tablets",
      "3 output ports (2 USB-A + 1 Type-C) – charge multiple devices",
      "Multiple input options (Type-C, Micro USB, Lightning)",
      "Smart LED display (battery %, voltage, current)",
      "Charge up to 3 devices at once",
      "Advanced safety protection system (overcharge, heat, short circuit)",
      "Strong, durable design (but a bit heavy)",
    ],
  },

  {
    id: 38,
    name: "Romoss 65W PD Fast Charge 27000mA USB-C Portable Powerful Laptop Power Bank",
    image: romossproduct.romoss9,
    images: [
      romossproduct.romoss9,
      romossproduct.romoss9b,
      romossproduct.romoss9c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "27000mAh high capacity (≈99.9Wh) – airline-safe & long backup",
      "65W fast charging (PD) – powers laptops & phones",
      "Laptop support (USB-C) – MacBook, Dell, HP, etc.",
      "Multiple ports – 2 USB-C + 2 USB-A (charge up to 4 devices)",
      "Fast recharge (~3 hours with 65W charger.",
      "Smart LED digital display (battery %, status)",
      "Wide compatibility (phones, tablets, laptops)",
      "Advanced safety protection system",
    ],
  },

  {
    id: 39,
    name: "ROMOSS PEA20 20000mAh Power Bank with 30W Fast Charging",
    image: romossproduct.romoss10,
    images: [
      romossproduct.romoss10,
      romossproduct.romoss10b,
      romossproduct.romoss10c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20000mAh capacity — good multi-day phone backup",
      "30W fast charging (PD + QC) — quick power for phones & tablets",
      "Multiple ports – USB-C + USB-A (charge 2 devices at once)",
      "Type-C two-way charging (input & output)",
      "LED digital display — battery %, status",
      "Broad device compatibility — phones, tablets, earbuds",
      "Smart safety protections (overcharge, overheat, short circuit)",
      "Portable & travel-friendly design",
    ],
  },

  {
    id: 40,
    name: "Romoss 20000mAh Premium Mobile Device Power Bank (3 Input Ports)",
    image: romossproduct.romoss11,
    images: [
      romossproduct.romoss11,
      romossproduct.romoss11b,
      romossproduct.romoss11c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20000mAh capacity — charges phones multiple times",
      "Fast charging support (up to ~18–22.5W depending on variant)",
      "Dual ports (USB-A + Type-C) — charge 2 devices at once",
      "Type-C two-way charging (input & output)",
      "LED/indicator lights — battery level display",
      "Wide device compatibility (phones, tablets, accessories)",
      "Safety protections (overcharge, heat, short circuit)",
      "Slim & portable design — easy to carry",
    ],
  },

  {
    id: 41,
    name: "Romoss PAC20 Portable Charger 20000mAh, PD 22.5W Fast Charging Power Bank with Built in Cables, 3 Output 2 Input USB C",
    image: romossproduct.romoss12,
    images: [
      romossproduct.romoss12,
      romossproduct.romoss12b,
      romossproduct.romoss12c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20000mAh capacity — multiple phone charges",
      "Fast charging support — efficient output for phones & tablets",
      "Multiple ports (USB-A + Type-C) — charge 2 devices at once",
      "Type-C two-way charging (input & output)",
      "Digital LED display (battery percentage)",
      "LED battery level display",
      "Wide compatibility — phones, tablets, accessories",
      "Smart safety protection (overcharge, overheating, short circuit)",
      "Compact & portable design",
    ],
  },

  {
    id: 42,
    name: "Romoss 6F 20000mAh 22.5W Fast Charge Portable Type-C Power Bank",
    image: romossproduct.romoss13,
    images: [
      romossproduct.romoss13,
      romossproduct.romoss13b,
      romossproduct.romoss13c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "22.5W fast charging (PD + QC support) — quick top-ups",
      "Dual output ports (USB-A + Type-C) — charge 2 devices at once",
      "Type-C two-way charging (input & output) — fast recharge + fast output",
      "LED digital battery display — exact % shown",
      "Compatible with phones, tablets & accessories",
      "Safety protection system — overcharge, overheat, short circuit",
      "Compact & portable design",
    ],
  },

  {
    id: 43,
    name: "Romoss Ares 20 Power Bank 20000mAh USB Type-C",
    image: romossproduct.romoss14,
    images: [
      romossproduct.romoss14,
      romossproduct.romoss14b,
      romossproduct.romoss14c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20000mAh capacity — multiple phone charges",
      "22.5W fast charging (PD + QC support) — quick top-ups",
      "Dual output ports (USB-A + Type-C) — charge 2 devices at once",
      "Type-C two-way charging (input & output) — fast recharge + fast output",
      "LED digital battery display — exact % shown",
      "Compatible with phones, tablets & accessories",
      "Safety protection system — overcharge, overheat, short circuit",
      "Compact & portable design",
    ],
  },

  {
    id: 44,
    name: "Romoss SW20PF 20000mAh 22.5W Power Bank",
    image: romossproduct.romoss15,
    images: [
      romossproduct.romoss15,
      romossproduct.romoss15b,
      romossproduct.romoss15c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20000mAh capacity — multiple phone charges",
      "Fast charging (up to ~22.5W PD/QC) — quick power for phones & tablets",
      "Multiple output ports (USB-A + Type-C) — charge 2 devices simultaneously",
      "Type-C two-way charging (input & output) — fast in & out",
      "LED digital display — shows battery percentage/status",
      "Wide device compatibility — phones, tablets, accessories",
      "Safety protections — overcharge/overheat/short-circuit guard",
      "Compact, travel-friendly design",
    ],
  },

  {
    id: 45,
    name: "Romoss PPU20 20000MAH BIDIRECTIONAL LAPTOP POWER BANK 130W FAST CHARGING ",
    image: romossproduct.romoss16,
    images: [
      romossproduct.romoss16,
      romossproduct.romoss16b,
      romossproduct.romoss16c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20000mAh high capacity",
      "130W ultra-fast charging",
      "Laptop ready PD support",
      "Multiple outputs",
      "65W fast recharge",
      "LED digital display",
      "Smart safety protections",
      "Portable, premium build",
    ],
  },
];
