import {
  itelwatts500,
  itelwatts130,
  itelwatts8000,
  linkotanks,
  batterys,
  inverters,
  panels,
  ecoflowtank,
} from "./solartankgen";

export const solartankproducts = [
  {
    id: 1,
    name: "itel Power Tank 500W Inverter + 1kWh LiFePO4 Battery All-in-One Solar Power Station",
    image: itelwatts500.itel5001b,
    images: [
      itelwatts500.itel5001,
      itelwatts500.itel5001b,
      itelwatts500.itel5001c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "1000Wh (1kWh) large battery",
      "500W output (1000W surge)",
      "Multiple ports (AC, USB, DC)",
      "Solar compatible — can charge with solar panel",
      "Dual charging (AC + solar)",
      "Silent & no fuel — no noise, no generator stress",
      "LCD/LED display — shows battery status",
      "Advanced protection system — safe & durable battery",
      "Portable design (~7kg) — easy to move around",
    ],
  },
  {
    id: 2,
    name: "itel 100,000mAh 320Wh - Portable Power Station 130W Fast Charging, LiFePO4 Battery IESS-320T",
    image: itelwatts130.itel1301,
    images: [
      itelwatts130.itel1301,
      itelwatts130.itel1301b,
      itelwatts130.itel1301c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "100,000mAh (≈320Wh) capacity",
      "130W total output",
      "USB-C fast charging (up to 65–100W)",
      "Multiple ports (USB-C, USB-A, DC)",
      "Solar + AC charging support",
      "Fast recharge (up to 100W input)",
      "Silent operation (no fuel, no noise)",
      "Built-in LED light",
      "Portable (~3.5kg) — easy to carry",
    ],
  },
  {
    id: 3,
    name: "itel ITEL. 3.6kW Inverter, 8kWh Battery & 5kw MPPT All-in-One Solar Power System - Complete Energy Storage Solution",
    image: itelwatts8000.itel80001b,
    images: [
      itelwatts8000.itel80001,
      itelwatts8000.itel80001b,
      itelwatts8000.itel80001c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "8000Wh (8kWh) massive battery",
      "3600W inverter (8000W surge)",
      "Multiple outputs (AC, USB, DC)",
      "Solar + PHCN charging",
      "Fast recharge system — up to 3000W AC + solar input",
      "UPS function (<16ms switch) — no light interruption",
      "LED display — shows system status & battery level",
      "Advanced protection system",
      "6000+ battery life cycles — long lifespan",
      "Whole-home backup solution — not a normal power bank",
    ],
  },
  {
    id: 4,
    name: "LINKCO Super Mini Power Station – (200Wh) Portable Power Bank AC/DC/USB/Type-C Outputs",
    image: linkotanks.linkotank1,
    images: [
      linkotanks.linkotank1,
      linkotanks.linkotank1b,
      linkotanks.linkotank1c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "200Wh (≈60,000mAh) capacity",
      "Up to ~100W AC output",
      "Multiple ports — AC, USB-A, USB-C, DC (charge many devices)",
      "45W USB-C fast charging (PD)",
      "Solar charging support",
      "Fast recharge (≈6–7 hrs)",
      "LED light / bulbs included",
      "Built-in safety protection (BMS)",
      "Portable mini power station",
    ],
  },
  {
    id: 5,
    name: "EcoFlow E980 Portable Power Station",
    image: ecoflowtank.ecoflow1b,
    images: [ecoflowtank.ecoflow1b, ecoflowtank.ecoflow, ecoflowtank.ecoflow1c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Battery Capacity: 980Wh (≈ 1kWh)",
      "Battery Type: LiFePO₄ (long-life lithium)",
      "Ports: ~13–15 outputs (AC, USB, DC, car port)",
      "Charging Time: 0–100% in ~2 hours",
      "Solar Input: up to 500W",
      "Weight: ~12–13 kg",
      "Auto-switch (UPS): <30 ms (almost instant backup)",
      "Lifespan: ~3000+ charge cycles (~10 years use)",
    ],
  },

  {
    id: 6,
    name: "Itel 5.12kwh/24v (100ah) wall mounted lithium battery",
    image: batterys.battery2c,
    images: [batterys.battery2, batterys.battery2b, batterys.battery2c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "5kWh capacity (25.6V, 200Ah)",
      "24V system — works with medium/large inverters",
      "6000+ life cycles — long lifespan (10+ years)",
      "Smart BMS protection — safe & stable operation",
      "Supports heavy loads — fridge, TV, fans, even AC (with inverter)",
      "Solar compatible — perfect for solar + inverter setups",
      "Expandable (up to 15 units)",
      "LED display — shows battery status & voltage",
      "Wall-mount design — clean installation & space saving",
    ],
  },
  {
    id: 7,
    name: "Itel ESS 5kWh/48V Lithium Battery LV-IPL-51100",
    image: batterys.battery3c,
    images: [batterys.battery3, batterys.battery3b, batterys.battery3c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "5.12kWh capacity (51.2V, 100Ah)",
      "48V system — works with modern high-power inverters",
      "6000+ life cycles — lasts 10+ years",
      "Smart BMS protection — safe, stable performance",
      "High discharge (~100A) — handles heavy appliances",
      "Solar compatible — perfect for solar + inverter setups",
      "Expandable (up to 15–16 units)",
      "LED display + communication ports",
      "Wall-mount design — clean installation & space saving",
    ],
  },
  {
    id: 8,
    name: "Itel Energy 10.24kWh Lithium Battery – Long Backup for Homes, Clinics & Offices (LiFePO4 48V)",
    image: batterys.battery4b,
    images: [batterys.battery4, batterys.battery4b, batterys.battery4c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "10–10.24kWh capacity (51.2V, 200Ah)",
      "48V system — works with high-power inverters (6kW–12kW)",
      "6000+ life cycles — 10+ years lifespan",
      "Smart BMS protection — prevents overcharge, heat & short circuit",
      "High discharge (~150A–200A)",
      "Solar compatible — perfect for solar + inverter setups",
      "Expandable (up to 15–16 units)",
      "LED display + communication ports",
      "Wall-mount / stackable design",
      "Silent & maintenance-free — no noise like generator",
    ],
  },
  {
    id: 9,
    name: "Itel 16000Wh Lithium Battery Standing 48V 314Ah 16kWh IPL-51314Y Outdoor IP65",
    image: batterys.battery5,
    images: [batterys.battery5, batterys.battery5b, batterys.battery5c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "16kWh capacity (51.2V ~280–314Ah)",
      "48V system — works with high-power inverters (5kW–15kW+)",
      "6000+ life cycles — 10+ years lifespan",
      "High discharge (150A–200A+)",
      "Smart BMS (50+ protections) — safe & stable performance",
      "Solar compatible — ideal for solar + inverter setups",
      "Expandable (up to 15 units) — scale your system anytime",
      "LED display + communication ports (CAN/RS485)",
      "Heavy-duty metal design (~125kg)",
      "Silent & maintenance-free — no noise like generator",
    ],
  },
  {
    id: 10,
    name: "Itel ESS IP65 32kWh/48V Lithium Battery LV-IPL-51628H IP65",
    image: batterys.battery6b,
    images: [batterys.battery6, batterys.battery6b, batterys.battery6c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "32kWh massive capacity (51.2V system)",
      "48V high-power system — supports large inverters (10kW–20kW+)",
      "6000+ life cycles — 10+ years lifespan (LiFePO4 tech)",
      "Very high discharge (200A+ combined)",
      "Advanced Smart BMS — protects against overcharge, heat & short circuit",
      "Solar compatible — perfect for large solar installations",
      "Modular/stackable system — built by combining multiple units (e.g. 16kWh ×2)",
      "LCD/LED display + communication ports (CAN/RS485)",
      "Heavy-duty industrial design — built for continuous use",
      "Silent & maintenance-free — no generator noise",
    ],
  },

  {
    id: 11,
    name: "itel 1.5kw (1500W) Inverter Hybrid 12V IP54 1Phase IPV-1K512U",
    image: inverters.inverter1b,
    images: [inverters.inverter1, inverters.inverter1b, inverters.inverter1c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "1.5kW output (1500W) — powers TV, fan, lights, small fridge",
      "12V battery system — affordable & easy setup",
      "3000W surge capacity",
      "1-phase inverter — standard for homes & small shops",
      "Built-in MPPT solar charger (≈45A)",
      "Fast auto switch (~20ms)",
      "Pure sine wave output — safe for electronics",
      "Quiet operation — low noise cooling system",
      "Full protection system — overload, heat, short circuit",
      "IP54 design — dust & splash resistant",
    ],
  },

  {
    id: 12,
    name: "itel 3kw Inverter Off-Grid (3000W) 24V IP54 1Phase IPV-3K24UPRO 4000W PV input",
    image: inverters.inverter2b,
    images: [inverters.inverter2, inverters.inverter2b, inverters.inverter2c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "3kW output (3000W) — powers TV, fridge, fans, lights, small AC",
      "24V battery system — more stable & efficient than 12V",
      "High surge (4.5kW–6kW)",
      "1-phase inverter",
      "Built-in MPPT solar charger (~99.9% efficiency)",
      "Fast auto switch (10–20ms)",
      "Pure sine wave",
      "Supports lithium & lead-acid batteries",
      "Full protection system",
      "IP54 design",
    ],
  },

  {
    id: 13,
    name: "itel 4kw Inverter Hybrid 24V IP54 1Phase IPV-4K24UPRO with wifi",
    image: inverters.inverter3b,
    images: [inverters.inverter3, inverters.inverter3b, inverters.inverter3c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "4kW output (4000W)",
      "8kW surge capacity",
      "24V battery system",
      "High MPPT efficiency (~99.9%)",
      "Fast charging (up to 120A MPPT)",
      "Fast auto switch (~10ms)",
      "Pure sine wave output",
      "Hybrid system",
      "IP54 design",
      "Smart features (WiFi)",
    ],
  },

  {
    id: 14,
    name: "itel 6kw Inverter Hybrid 48V IP54 1Phase IPV-6K48U",
    image: inverters.inverter4b,
    images: [inverters.inverter4, inverters.inverter4b, inverters.inverter4c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "6kW output (6000W)",
      "12,000W surge capacity",
      "48V battery system",
      "High MPPT efficiency",
      "Up to 8000W solar input",
      "Fast charging",
      "Fast auto switch",
      "Parallel support",
      "Smart monitoring",
      "IP54 protection",
    ],
  },

  {
    id: 15,
    name: "Itel 410W Solar Panel 20.97% module efficiency with 108 Mono cells (1722*1134*30mm) ODA410-27V-МHP",
    image: panels.panel1b,
    images: [panels.panel1, panels.panel1b, panels.panel1c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "410W high output",
      "Monocrystalline cells",
      "Durable aluminum frame",
      "IP65 / IP67 rated",
      "MC4 connectors",
      "Low temperature coefficient",
      "Ideal for home systems",
      "Easy installation",
    ],
  },

  {
    id: 16,
    name: "Itel 590W Solar Panel N-Type Mono cells Bifacial",
    image: panels.panel2b,
    images: [panels.panel2, panels.panel2b, panels.panel2c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "590W high output",
      "Monocrystalline cells",
      "Durable aluminum frame",
      "IP65 / IP67 rated",
      "MC4 connectors",
      "Low temperature coefficient",
      "Ideal for large solar systems",
      "Easy installation",
    ],
  },
  {
    id: 17,
    name: "Itel 2560Wh Lithium Battery Wall Mounted 24V 100Ah 2.56kWh IPW-25100x",
    image: batterys.battery1b,
    images: [batterys.battery1, batterys.battery1b, batterys.battery1c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "2.5kWh capacity (≈100Ah, 25.6V)",
      "24V system battery — ideal for small/medium inverters",
      "6000+ life cycles — long lifespan (years of use)",
      "Smart BMS protection — prevents overcharge, heat & short circuit",
      "High discharge (up to ~100A)",
      "Fast charging support — efficient recharge with inverter/solar",
      "Solar compatible — perfect for solar setups",
      "Lightweight lithium design (~25–30kg)",
      "Expandable (parallel support)",
    ],
  },
];
