import {
  baseusproduct,
  infinixproduct,
  itelproduct,
  linkoproduct,
} from "./powerbankdummy/powerbankgen";

import {
  itelwatts500,
  itelwatts130,
  itelwatts8000,
  linkotanks,
  batterys,
  ecoflowtank,
} from "./solartankdummy/solartankgen";

import { menslidesproduct, womenslidesproduct } from "./shoedummy/shoegen";
import {
  fridgeproduct,
  genproduct,
  teleproduct,
  washproduct,
} from "./electronicdummy/electronicgen";

export const powerbankproducts = [
  {
    id: 1,
    name: "Baseus 20,000mAh 65W Power Bank",
    image: baseusproduct.baseus1,
    images: [
      baseusproduct.baseus1,
      baseusproduct.baseus2,
      baseusproduct.baseus3,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "65W Power Delivery fast charging",
      "20,000mAh high-capacity battery",
      "Charge up to 5 devices simultaneously",
      "Digital display for battery level",
      "Dual USB + USB-C ports",
      "Fast recharge (≈2.5 hours with 60W charger)",
      "Compatible with phones, tablets & laptops",
      "Sleek and portable design",
    ],
  },

  {
    id: 2,
    name: "Infinix 10000mAH Power Bank USB C In/out Xpower10",
    image: infinixproduct.infinix1,
    images: [
      infinixproduct.infinix1,
      infinixproduct.infinix1b,
      infinixproduct.infinix1c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Capacity - 10,000mah",
      "Power rated input 12W",
      "Power output 12W",
      "USB output port - 2usb 1 typeC",
      "TypeC support - dual",
      "Infinix Xpower10",
      "Compatible with phones & tablets",
      "Sleek and portable design",
    ],
  },

  {
    id: 3,
    name: "Infinix 20000mAH Power Bank USB C In/out Xpower20 Go",
    image: infinixproduct.infinix2,
    images: [
      infinixproduct.infinix2,
      infinixproduct.infinix2b,
      infinixproduct.infinix2c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20000mAh Capacity - Charge multiple devices several times",
      "Fast Charging - Quick, efficient power for phones and tablets",
      "Dual USB + Type-C Ports - Charge two devices at the same time",
      "Compact & Portable - Easy to carry for travel or daily use",
      "Dual USB + USB-C ports",
      "Smart Safety Features - Protects devices from overcharge, overheat, and short circuits",
      "Compatible with phones & tablets",
      "Sleek and portable design",
    ],
  },

  {
    id: 4,
    name: "Infinix Gt Power 20000mAh 55W Portable Laptop Charging Powerbank",
    image: infinixproduct.infinix3,
    images: [
      infinixproduct.infinix3,
      infinixproduct.infinix3b,
      infinixproduct.infinix3c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    description: "",
    features: [
      "1 year warranty",
      "55W Super Fast Laptop Charging Speed",
      "Attached type C braided cable (55W)",
      "Attached cable also act as lanyard",
      "Type C out port (In and Out)",
      "20000mAh capacity",
      "Compatible with phones & tablets",
      "Digital power display",
    ],
  },

  {
    id: 5,
    name: "itel 40000mAh 22.5W Fast Charging Type-C Output Powerbank",
    image: itelproduct.itel1,
    images: [itelproduct.itel1, itelproduct.itel1b, itelproduct.itel1c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "40,000mAh Large Capacity",
      "22.5 Watts Fast Charging",
      "4 x  USB Output, 2 x Type-C Input and Output",
      "Up to 22.5W Fast Charging for 6 devices",
      "Bright Torch",
      "12 Months Warranty by Carlcare",
      "Up to 6 times Phone Charging",
      "Type-C Input and Output",
      "Anti-Slip Texture",
      "Certified Safe: 10 Security Protection",
    ],
  },

  {
    id: 6,
    name: "itel 27000mAh 65W Type-C Phone & Laptop Power Bank With Torch",
    image: itelproduct.itel2,
    images: [itelproduct.itel2, itelproduct.itel2b, itelproduct.itel2c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Power LAPTOPS & TABLETS with Type-C Port",
      "65W Fast Charging Type-C In & Out",
      "Flight Friendly",
      "27,000mAh Massive Capacity",
      "Charge up to 4 devices at once",
      "Four Ports (3 USB-A, 1 Type-C In & Out)",
      "Up to 7x Charges",
      "Output Type-C:  5V 3A, 9V 3A, 12V 3A, 15V 3A, 20V 3.25A (65W Max)",
      "Input Type-C:  5V 3A, 9V 3A, 12V 3A, 15V 3A, 20V 3.25A (65W Max) ",
      "Universal Compatibility27,000mAh Large Capacity",
    ],
  },

  {
    id: 7,
    name: "Itel 27000mAh 22.5W Fast Charging Power Bank + Free 18W Charger",
    image: itelproduct.itel3,
    images: [itelproduct.itel3, itelproduct.itel3b, itelproduct.itel3c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "27,000mAh Large Capacity",
      "Free 18 Watts Fast Charger",
      "22.5 Watts Fast Charging",
      "Bright Torch",
      "3 x  USB Output, 1 x Type-C Output",
      "Up to 22.5W Fast Charging for Four",
      "Up to 4.5 times Phone Charging",
      "Type-C Input and Output",
      "Anti-Slip Texture",
      "Certified Safe: 10 Security Protection",
      "super fast",
    ],
  },

  {
    id: 8,
    name: "itel 20000mAh 15W Fast Charging Type-C Output Star200P Power Bank",
    image: itelproduct.itel4,
    images: [itelproduct.itel4, itelproduct.itel4b, itelproduct.itel4c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "20,000mAh Strong Capacity",
      "15Watts Fast Charging",
      "Digital Display",
      "Micro USB & Type-C Dual Input",
      "Up to 3A Fast Charging for up to 3 Devices",
      "12 Months Warranty by Carlcare",
      "Anti-Slip Texture",
      "Certified Safe: Itel Superior Safety",
    ],
  },

  {
    id: 9,
    name: "Itel 27000mAh 22.5W Fast Charging Power Bank + Free 18W Charger",
    image: itelproduct.itel5,
    images: [itelproduct.itel5, itelproduct.itel5b, itelproduct.itel5c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "27,000mAh Large Capacity",
      "Free 18 Watts Fast Charger",
      "22.5 Watts Fast Charging",
      "Bright Torch",
      "3 x  USB Output, 1 x Type-C Output",
      "Up to 22.5W Fast Charging for Four",
      "Up to 4.5 times Phone Charging",
      "Type-C Input and Output",
      "Anti-Slip Texture",
      "Certified Safe: 10 Security Protection",
      "super fast",
    ],
  },

  {
    id: 10,
    name: "LINKCO 50000 mAh Fast Charging Powerbank 22.5W With Bright Torch",
    image: linkoproduct.linko1,
    images: [linkoproduct.linko1, linkoproduct.linko1b, linkoproduct.linko1c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "50,000mAh Large Capacity",
      "Up to 22.5W Fast Charging for Four",
      "3 x  USB Output, 1 x Type-C Output",
      "Dual Input: 1 x Type-C, 1 x Micro USB",
      "With Bright Torch",
      "12 Months Warranty",
      "Up to 10 times Phone Charging",
      "Type-C Input and Output",
      "Certified Safe: Security Protection",
    ],
  },
];

export const solartankproducts = [
  {
    id: 1,
    name: "itel Power Tank 500W Inverter + 1kWh LiFePO4 Battery All-in-One Solar Power Station",
    image: itelwatts500.itel5001b,
    images: [
      itelwatts500.itel5001,
      itelwatts500.itel5001b,
      itelwatts500.itel5001c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "1000Wh (1kWh) large battery",
      "500W output (1000W surge)",
      "Multiple ports (AC, USB, DC)",
      "Solar compatible — can charge with solar panel",
      "Dual charging (AC + solar)",
      "Silent & no fuel — no noise, no generator stress",
      "LCD/LED display — shows battery status",
      "Advanced protection system — safe & durable battery",
      "Portable design (~7kg) — easy to move around",
    ],
  },
  {
    id: 2,
    name: "itel 100,000mAh 320Wh - Portable Power Station 130W Fast Charging, LiFePO4 Battery IESS-320T",
    image: itelwatts130.itel1301,
    images: [
      itelwatts130.itel1301,
      itelwatts130.itel1301b,
      itelwatts130.itel1301c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "100,000mAh (≈320Wh) capacity",
      "130W total output",
      "USB-C fast charging (up to 65–100W)",
      "Multiple ports (USB-C, USB-A, DC)",
      "Solar + AC charging support",
      "Fast recharge (up to 100W input)",
      "Silent operation (no fuel, no noise)",
      "Built-in LED light",
      "Portable (~3.5kg) — easy to carry",
    ],
  },
  {
    id: 3,
    name: "itel ITEL. 3.6kW Inverter, 8kWh Battery & 5kw MPPT All-in-One Solar Power System - Complete Energy Storage Solution",
    image: itelwatts8000.itel80001b,
    images: [
      itelwatts8000.itel80001,
      itelwatts8000.itel80001b,
      itelwatts8000.itel80001c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "8000Wh (8kWh) massive battery",
      "3600W inverter (8000W surge)",
      "Multiple outputs (AC, USB, DC)",
      "Solar + PHCN charging",
      "Fast recharge system — up to 3000W AC + solar input",
      "UPS function (<16ms switch) — no light interruption",
      "LED display — shows system status & battery level",
      "Advanced protection system",
      "6000+ battery life cycles — long lifespan",
      "Whole-home backup solution — not a normal power bank",
    ],
  },
  {
    id: 4,
    name: "LINKCO Super Mini Power Station – (200Wh) Portable Power Bank AC/DC/USB/Type-C Outputs",
    image: linkotanks.linkotank1,
    images: [
      linkotanks.linkotank1,
      linkotanks.linkotank1b,
      linkotanks.linkotank1c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "200Wh (≈60,000mAh) capacity",
      "Up to ~100W AC output",
      "Multiple ports — AC, USB-A, USB-C, DC (charge many devices)",
      "45W USB-C fast charging (PD)",
      "Solar charging support",
      "Fast recharge (≈6–7 hrs)",
      "LED light / bulbs included",
      "Built-in safety protection (BMS)",
      "Portable mini power station",
    ],
  },

  {
    id: 5,
    name: "EcoFlow E980 Portable Power Station",
    image: ecoflowtank.ecoflow1b,
    images: [ecoflowtank.ecoflow1b, ecoflowtank.ecoflow, ecoflowtank.ecoflow1c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Battery Capacity: 980Wh (≈ 1kWh)",
      "Battery Type: LiFePO₄ (long-life lithium)",
      "Ports: ~13–15 outputs (AC, USB, DC, car port)",
      "Charging Time: 0–100% in ~2 hours",
      "Solar Input: up to 500W",
      "Weight: ~12–13 kg",
      "Auto-switch (UPS): <30 ms (almost instant backup)",
      "Lifespan: ~3000+ charge cycles (~10 years use)",
    ],
  },
  {
    id: 6,
    name: "Itel 5.12kwh/24v (100ah) wall mounted lithium battery",
    image: batterys.battery2c,
    images: [batterys.battery2, batterys.battery2b, batterys.battery2c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "5kWh capacity (25.6V, 200Ah)",
      "24V system — works with medium/large inverters",
      "6000+ life cycles — long lifespan (10+ years)",
      "Smart BMS protection — safe & stable operation",
      "Supports heavy loads — fridge, TV, fans, even AC (with inverter)",
      "Solar compatible — perfect for solar + inverter setups",
      "Expandable (up to 15 units)",
      "LED display — shows battery status & voltage",
      "Wall-mount design — clean installation & space saving",
    ],
  },
  {
    id: 7,
    name: "Itel ESS 5kWh/48V Lithium Battery LV-IPL-51100",
    image: batterys.battery3c,
    images: [batterys.battery3, batterys.battery3b, batterys.battery3c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "5.12kWh capacity (51.2V, 100Ah)",
      "48V system — works with modern high-power inverters",
      "6000+ life cycles — lasts 10+ years",
      "Smart BMS protection — safe, stable performance",
      "High discharge (~100A) — handles heavy appliances",
      "Solar compatible — perfect for solar + inverter setups",
      "Expandable (up to 15–16 units)",
      "LED display + communication ports",
      "Wall-mount design — clean installation & space saving",
    ],
  },
  {
    id: 8,
    name: "Itel Energy 10.24kWh Lithium Battery – Long Backup for Homes, Clinics & Offices (LiFePO4 48V)",
    image: batterys.battery4b,
    images: [batterys.battery4, batterys.battery4b, batterys.battery4c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "10–10.24kWh capacity (51.2V, 200Ah)",
      "48V system — works with high-power inverters (6kW–12kW)",
      "6000+ life cycles — 10+ years lifespan",
      "Smart BMS protection — prevents overcharge, heat & short circuit",
      "High discharge (~150A–200A)",
      "Solar compatible — perfect for solar + inverter setups",
      "Expandable (up to 15–16 units)",
      "LED display + communication ports",
      "Wall-mount / stackable design",
      "Silent & maintenance-free — no noise like generator",
    ],
  },
  {
    id: 9,
    name: "Itel 16000Wh Lithium Battery Standing 48V 314Ah 16kWh IPL-51314Y Outdoor IP65",
    image: batterys.battery5,
    images: [batterys.battery5, batterys.battery5b, batterys.battery5c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "16kWh capacity (51.2V ~280–314Ah)",
      "48V system — works with high-power inverters (5kW–15kW+)",
      "6000+ life cycles — 10+ years lifespan",
      "High discharge (150A–200A+)",
      "Smart BMS (50+ protections) — safe & stable performance",
      "Solar compatible — ideal for solar + inverter setups",
      "Expandable (up to 15 units) — scale your system anytime",
      "LED display + communication ports (CAN/RS485)",
      "Heavy-duty metal design (~125kg)",
      "Silent & maintenance-free — no noise like generator",
    ],
  },
  {
    id: 10,
    name: "Itel ESS IP65 32kWh/48V Lithium Battery LV-IPL-51628H IP65",
    image: batterys.battery6b,
    images: [batterys.battery6, batterys.battery6b, batterys.battery6c],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "32kWh massive capacity (51.2V system)",
      "48V high-power system — supports large inverters (10kW–20kW+)",
      "6000+ life cycles — 10+ years lifespan (LiFePO4 tech)",
      "Very high discharge (200A+ combined)",
      "Advanced Smart BMS — protects against overcharge, heat & short circuit",
      "Solar compatible — perfect for large solar installations",
      "Modular/stackable system — built by combining multiple units (e.g. 16kWh ×2)",
      "LCD/LED display + communication ports (CAN/RS485)",
      "Heavy-duty industrial design — built for continuous use",
      "Silent & maintenance-free — no generator noise",
    ],
  },
];

export const shoeproducts = [
  {
    id: 1,
    name: "Classic & Simple Male Black Crossed Pam Slips - (BLACK)",
    image: menslidesproduct.male1,
    images: [
      menslidesproduct.male1,
      menslidesproduct.male1b,
      menslidesproduct.male1c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Fashionable & Breathable",
      "Comfortable to wear",
      "Material: High-quality premium leather.",
      "Made of good quality material",
      "Excellent workmanship & Hard-wearing",
      "Color: Midnight Black with Gold and Cyan accents.",
    ],
  },

  {
    id: 2,
    name: "The Royal Heritage Slide (Classic & Prestigious)",
    image: menslidesproduct.male2,
    images: [
      menslidesproduct.male2,
      menslidesproduct.male2b,
      menslidesproduct.male2c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Upper: High-grade velvet and supple calfskin leather.",
      "Sole: Durable, low-profile black rubberized outsole.",
      "Accents: Polished gold-metallic hardware on the upper and heel.",
      "Fashionable & Breathable",
      "Comfortable to wear",
      "Material: High-quality premium leather.",
    ],
  },

  {
    id: 3,
    name: "The Signature Quilt-Stitch Slide",
    image: menslidesproduct.male3,
    images: [
      menslidesproduct.male3,
      menslidesproduct.male3b,
      menslidesproduct.male3c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Style: Padded Crisscross Slide",
      "Material: Supple Calf Leather",
      "Texture: Defined Channel-Quilting",
      "Footbed: Ergonomic Padded Insole",
      "Outsole: Durable Low-Profile Leather/Rubber Hybrid",
      "Hardware: Minimalist, Branding Discreet",
      "Colors Available: Midnight Black, Charcoal Olive, and Tan Brown",
      "Production: Hand-crafted, Bench-made Quality",
      "Availability: Limited Production Run",
    ],
  },

  {
    id: 4,
    name: "Zara Man Woven Leather Heritage Slides",
    image: menslidesproduct.male4,
    images: [
      menslidesproduct.male4,
      menslidesproduct.male4b,
      menslidesproduct.male4c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Contemporary H-strap woven silhouette with an open-toe profile.",
      "Premium matte synthetic leather upper for a sleek, durable finish.",
      "Ergonomically cushioned black footbed featuring high-contrast ZARA branding.",
      "High-traction, textured rubber sole for enhanced grip and stability.",
      "Deep Espresso Brown upper with a Charcoal Black base.",
      "Slip-on construction designed for effortless wear and a secure, comfortable fit.",
      "Ideal for home & inverter solar systems — pairs well with 5kWh+ batteries",
      "Easy installation (roof/ground) — lightweight and robust",
    ],
  },

  {
    id: 5,
    name: "The Urban Cross-Strap Leather Slide",
    image: menslidesproduct.male5,
    images: [
      menslidesproduct.male5,
      menslidesproduct.male5b,
      menslidesproduct.male5c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Ultra-soft, premium synthetic leather with high-density foam padding.",
      "Dual wide criss-cross straps with linear quilted stitching",
      "Ergonomically contoured, smooth-finish insole for a soft landing with every step.",
      "Low-profile, flexible rubber sole with integrated grip patterns for indoor and outdoor versatility.",
      "Slip-on open-toe construction for maximum breathability.",
      "Color Availability:",
      ". Pitch Black: Bold and versatile",
      "Olive Drab: A subtle, earthy neutral.",
      "Saddle Tan: Warm, rich, and classic.",
    ],
  },
  {
    id: 17,
    name: "MANGO Criss-Cross Strap Comfort Slides",
    image: womenslidesproduct.female1,
    images: [
      womenslidesproduct.female1,
      womenslidesproduct.female1b,
      womenslidesproduct.female1c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Criss-cross straps",
      "Synthetic leather",
      "Cushioned footbed",
      "Rubber sole",
      "Tan / Black",
    ],
  },

  {
    id: 18,
    name: "Vibrant Triple-Strap Platform Wedge Slides",
    image: womenslidesproduct.female2,
    images: [
      womenslidesproduct.female2,
      womenslidesproduct.female2b,
      womenslidesproduct.female2c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Platform wedge",
      "Soft fabric",
      "Open-toe",
      "EVA sole",
      "3-4 inch height",
    ],
  },

  {
    id: 19,
    name: "Urban Nomad Dual-Strap Leather Slides",
    image: womenslidesproduct.female3,
    images: [
      womenslidesproduct.female3,
      womenslidesproduct.female3b,
      womenslidesproduct.female3c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: ["Leather", "Double strap", "Ergonomic", "Slip-on", "Casual"],
  },

  {
    id: 20,
    name: "ZARA Collection Quilted Criss-Cross Embellished Slides",
    image: womenslidesproduct.female4,
    images: [
      womenslidesproduct.female4,
      womenslidesproduct.female4b,
      womenslidesproduct.female4c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Quilted straps",
      "Charms",
      "Padded leather",
      "Multiple colors",
      "Stylish",
    ],
  },

  {
    id: 21,
    name: "Chic Criss-Cross Buckle Flat Slides",
    image: womenslidesproduct.female5,
    images: [
      womenslidesproduct.female5,
      womenslidesproduct.female5b,
      womenslidesproduct.female5c,
    ],
    price: "₦18,000",
    oldPrice: "₦22,000",
    features: [
      "Flat slides",
      "Vegan leather",
      "Square toe",
      "Rubber sole",
      "Casual",
    ],
  },
];

export const electronics = [
  {
    id: 1,
    name: "LG 43-Inch Smart LED TV",
    image: teleproduct.tele1,
    images: [teleproduct.tele1, teleproduct.tele1b, teleproduct.tele1c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Screen Size: 43 Inches",
      "Resolution: Full HD (1920 × 1080)",
      "Display Type: LED",
      "Smart TV: Yes (webOS)",
      "Audio Output: 20W (2 Speakers)",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
      "HDR Support: HDR10 & HLG",
    ],
  },
  {
    id: 2,
    name: "LG 50-Inch UHD 4K Smart LED TV",
    image: teleproduct.tele2,
    images: [teleproduct.tele2, teleproduct.tele2b, teleproduct.tele2c],
    price: "₦500,000",
    oldPrice: "₦525,000",
    features: [
      "Screen Size: 50 Inches",
      "Resolution: 4K UHD (3840 × 2160)",
      "Display Type: LED",
      "Smart TV: Yes (webOS with streaming apps)",
      "Processor: α5 AI Processor 4K",
      "Audio Output: 20W (2.0 Channel Speakers)",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
    ],
  },

  {
    id: 11,
    name: "Senwei 1.5KVA Portable Petrol Generator",
    image: genproduct.gen1,
    images: [genproduct.gen1, genproduct.gen1b, genproduct.gen1c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Power Output: 1.5KVA (≈ 1000W – 1200W running load)",
      "Fuel Type: Petrol (Gasoline Engine)",
      "Starting System: Manual (Recoil Start)",
      "Engine Type: 4-Stroke, Air-Cooled, Single Cylinder",
      "Voltage: 220V – 240V / 50Hz",
      "Fuel Tank Capacity: Approx. 4–8 Litres",
      "Design: Portable, Low Noise, Lightweight",
    ],
  },
  {
    id: 12,
    name: "Firman 1.5KVA Portable Petrol Generator",
    image: genproduct.gen2,
    images: [genproduct.gen2, genproduct.gen2b, genproduct.gen2c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Power Output: 1.5KVA (≈ 1000W – 1500W running load)",
      "Fuel Type: Petrol (Gasoline Engine)",
      "Starting System: Manual (Recoil Start)",
      "Engine Type: 4-Stroke, Single Cylinder, Air-Cooled (≈ 3.8HP)",
      "Voltage: 220V / 50Hz (Single Phase)",
      "Fuel Tank Capacity: 5.5 – 8 Litres",
      "Design: Portable, Low Noise (≈63–68 dB), 100% Copper Coil",
    ],
  },

  {
    id: 16,
    name: "Hisense 5KG Twin Tub Washing Machine",
    image: washproduct.wash1,
    images: [washproduct.wash1, washproduct.wash1b, washproduct.wash1c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 5KG Wash & Spin",
      "Type: Twin Tub (Wash + Spin Dryer)",
      "Loading Type: Top Load",
      "Body Design: Rust-proof Plastic Body",
      "Control: Manual Knobs (User-friendly panel)",
      "Special Features: Lint Filter & Water Selector",
      "Drum: Durable Inner Tub (Efficient washing performance)",
    ],
  },
  {
    id: 17,
    name: "Hisense 7.5KG Twin Tub Washing Machine",
    image: washproduct.wash2,
    images: [washproduct.wash2, washproduct.wash2b, washproduct.wash2c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 7.5KG Wash & Spin",
      "Type: Twin Tub (Wash + Spin Dryer)",
      "Loading Type: Top Load (Semi-Automatic)",
      "Body Design: Rust-proof Plastic Body",
      "Control: Manual Knobs (User-friendly panel)",
      "Special Features: Lint Filter & Water Selector",
      "Design: Classic, Durable Build (Twin Tub System)",
    ],
  },

  {
    id: 22,
    name: "Royal 105L Single Door Refrigerator",
    image: fridgeproduct.fridge1,
    images: [
      fridgeproduct.fridge1,
      fridgeproduct.fridge1b,
      fridgeproduct.fridge1c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 105 Litres (Compact size for small homes/offices)",
      "Type: Single Door (Direct Cool Technology)",
      "Cooling System: Fast & Even Cooling (Direct Cool)",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Compact, modern with adjustable shelves",
      "Special Features: Interior light, egg tray & vegetable box",
      "Extra: Lock system & adjustable thermostat",
    ],
  },
  {
    id: 23,
    name: "Hisense 90L",
    image: fridgeproduct.fridge2,
    images: [
      fridgeproduct.fridge2,
      fridgeproduct.fridge2b,
      fridgeproduct.fridge2c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 90 Litres (Compact size for small homes/offices)",
      "Type: Single Door (Direct Cool Technology)",
      "Cooling System: Fast & Efficient Cooling (Direct Cool)",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Compact, modern with durable shelves",
      "Special Features: Interior light, door compartments & freezer box",
      "Extra: Adjustable thermostat & low noise operation",
    ],
  },

  {
    id: 13,
    name: "Elepaq 3.5KVA Petrol Generator (Manual Start)",
    image: genproduct.gen3,
    images: [genproduct.gen3, genproduct.gen3b, genproduct.gen3c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Power Output: 3.5KVA (≈ 3000W running capacity)",
      "Fuel Type: Petrol (Gasoline Engine)",
      "Starting System: Manual (Recoil Start)",
      "Engine Type: 4-Stroke, Single Cylinder, Air-Cooled (OHV)",
      "Voltage: 220V / 50Hz (Single Phase)",
      "Fuel Tank Capacity: 15 Litres",
      "Noise Level: ≈ 63dB (Low Noise Design)",
    ],
  },

  {
    id: 18,
    name: "Hisense 11KG Twin Tub Washing Machine",
    image: washproduct.wash3,
    images: [washproduct.wash3, washproduct.wash3b, washproduct.wash3c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 11KG Wash & Spin (Large Family Size)",
      "Type: Twin Tub (Wash + Spin Dryer)",
      "Loading Type: Top Load (Semi-Automatic)",
      "Control: Manual Knobs (Easy operation)",
      "Body Design: Durable Rust-proof Plastic",
      "Special Features: Lint Filter & Water Selector",
      "Function: Wash & Spin simultaneously (Saves time)",
    ],
  },
];
