import {
  fridgeproduct,
  genproduct,
  teleproduct,
  washproduct,
} from "./electronicgen";

export const electronicsproducts = [
  // TELEVISION
  {
    id: 1,
    name: "LG 43-Inch Smart LED TV",
    image: teleproduct.tele1,
    images: [teleproduct.tele1, teleproduct.tele1b, teleproduct.tele1c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Screen Size: 43 Inches",
      "Resolution: Full HD (1920 × 1080)",
      "Display Type: LED",
      "Smart TV: Yes (webOS)",
      "Audio Output: 20W (2 Speakers)",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
      "HDR Support: HDR10 & HLG",
    ],
  },
  {
    id: 2,
    name: "LG 50-Inch UHD 4K Smart LED TV",
    image: teleproduct.tele2,
    images: [teleproduct.tele2, teleproduct.tele2b, teleproduct.tele2c],
    price: "₦500,000",
    oldPrice: "₦525,000",
    features: [
      "Screen Size: 50 Inches",
      "Resolution: 4K UHD (3840 × 2160)",
      "Display Type: LED",
      "Smart TV: Yes (webOS with streaming apps)",
      "Processor: α5 AI Processor 4K",
      "Audio Output: 20W (2.0 Channel Speakers)",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
    ],
  },
  {
    id: 3,
    name: "Hisense 32-Inch HD Smart LED TV",
    image: teleproduct.tele3,
    images: [teleproduct.tele3, teleproduct.tele3b, teleproduct.tele3c],
    price: "₦200,000",
    oldPrice: "₦235,000",
    features: [
      "Screen Size: 32 Inches",
      "Resolution: HD (1366 × 768)",
      "Display Type: LED (LCD Panel)",
      "Smart TV: Yes (VIDAA OS with Netflix & YouTube)",
      "Audio Technology: DTS Virtual:X Sound",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
      "Design: Slim Bezel / Bezel-less Design",
    ],
  },
  {
    id: 4,
    name: "Hisense 43-Inch 4K UHD Smart LED TV",
    image: teleproduct.tele4,
    images: [teleproduct.tele4, teleproduct.tele4b, teleproduct.tele4c],
    price: "₦330,000",
    oldPrice: "₦345,000",
    features: [
      "Screen Size: 43 Inches",
      "Resolution: 4K UHD (3840 × 2160)",
      "Display Type: LED (UHD Panel)",
      "Smart TV: Yes (VIDAA OS with Netflix & YouTube)",
      "Audio Technology: DTS Virtual:X / Dolby Audio",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
      "Refresh Rate: 60Hz",
    ],
  },
  {
    id: 5,
    name: "Hisense 50-Inch 4K UHD Smart LED TV",
    image: teleproduct.tele5,
    images: [teleproduct.tele5, teleproduct.tele5b, teleproduct.tele5c],
    price: "₦440,000",
    oldPrice: "₦465,000",
    features: [
      "Screen Size: 50 Inches",
      "Resolution: 4K UHD (3840 × 2160)",
      "Display Type: LED (Direct LED Backlight)",
      "Smart TV: Yes (VIDAA OS with Netflix & YouTube)",
      "Audio Technology: Dolby Audio / DTS Virtual:X",
      "Refresh Rate: 60Hz",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
    ],
  },
  {
    id: 6,
    name: "Hisense 55-Inch 4K UHD Smart LED TV",
    image: teleproduct.tele6,
    images: [teleproduct.tele6, teleproduct.tele6b, teleproduct.tele6c],
    price: "₦530,000",
    oldPrice: "₦545,000",
    features: [
      "Screen Size: 55 Inches",
      "Resolution: 4K UHD (3840 × 2160)",
      "Display Type: LED (UHD Panel)",
      "Smart TV: Yes (VIDAA OS with Netflix & YouTube)",
      "Audio Technology: Dolby Audio / DTS Virtual:X",
      "Refresh Rate: 60Hz",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
    ],
  },
  {
    id: 7,
    name: "Hisense 58-Inch 4K UHD Smart LED TV",
    image: teleproduct.tele7,
    images: [teleproduct.tele7, teleproduct.tele7b, teleproduct.tele7c],
    price: "₦580,000",
    oldPrice: "₦600,000",
    features: [
      "Screen Size: 58 Inches",
      "Resolution: 4K UHD (3840 × 2160)",
      "Display Type: LED (Direct LED Backlight)",
      "Smart TV: Yes (VIDAA OS with Netflix & YouTube)",
      "Audio Technology: Dolby Audio / DTS Virtual:X",
      "Refresh Rate: 60Hz (Game Mode supported)",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
    ],
  },
  {
    id: 8,
    name: "TCL 32-Inch HD/Full HD Smart LED TV",
    image: teleproduct.tele8,
    images: [teleproduct.tele8, teleproduct.tele8b, teleproduct.tele8c],
    price: "₦210,000",
    oldPrice: "₦225,000",
    features: [
      "Screen Size: 32 Inches",
      "Resolution: HD (1366 × 768) or Full HD (1920 × 1080)",
      "Display Type: LED",
      "Smart TV: Yes (Android TV with Google Assistant & Chromecast)",
      "Audio: Dolby Audio (2 × 8W Speakers)",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
      "Design: Slim / Bezel-less Design",
    ],
  },
  {
    id: 9,
    name: "LG 43-Inch Smart LED TV",
    image: teleproduct.tele9,
    images: [teleproduct.tele9, teleproduct.tele9b, teleproduct.tele9c],
    price: "₦345,000",
    oldPrice: "₦360,000",
    features: [
      "Screen Size: 43 Inches",
      "Resolution: Full HD (1920 × 1080)",
      "Display Type: LED",
      "Smart TV: Yes (webOS)",
      "Audio Output: 20W (2 Speakers)",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
      "HDR Support: HDR10 & HLG",
    ],
  },
  {
    id: 10,
    name: "TCL 50-Inch 4K UHD Smart LED TV",
    image: teleproduct.tele10,
    images: [teleproduct.tele10, teleproduct.tele10b, teleproduct.tele10c],
    price: "₦380,000",
    oldPrice: "₦22,000",
    features: [
      "Screen Size: 50 Inches",
      "Resolution: 4K UHD (3840 × 2160)",
      "Display Type: LED (Direct LED backlight)",
      "Smart TV: Yes (Google TV / Android TV with built-in apps like Netflix & YouTube)",
      "Audio: Dolby Audio (20W speakers)",
      "Refresh Rate: 60Hz (Game Mode supported)",
      "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
    ],
  },

  // GENERATORS (11–15)
  {
    id: 11,
    name: "Senwei 1.5KVA Portable Petrol Generator",
    image: genproduct.gen1,
    images: [genproduct.gen1, genproduct.gen1b, genproduct.gen1c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Power Output: 1.5KVA (≈ 1000W – 1200W running load)",
      "Fuel Type: Petrol (Gasoline Engine)",
      "Starting System: Manual (Recoil Start)",
      "Engine Type: 4-Stroke, Air-Cooled, Single Cylinder",
      "Voltage: 220V – 240V / 50Hz",
      "Fuel Tank Capacity: Approx. 4–8 Litres",
      "Design: Portable, Low Noise, Lightweight",
    ],
  },
  {
    id: 12,
    name: "Firman 1.5KVA Portable Petrol Generator",
    image: genproduct.gen2,
    images: [genproduct.gen2, genproduct.gen2b, genproduct.gen2c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Power Output: 1.5KVA (≈ 1000W – 1500W running load)",
      "Fuel Type: Petrol (Gasoline Engine)",
      "Starting System: Manual (Recoil Start)",
      "Engine Type: 4-Stroke, Single Cylinder, Air-Cooled (≈ 3.8HP)",
      "Voltage: 220V / 50Hz (Single Phase)",
      "Fuel Tank Capacity: 5.5 – 8 Litres",
      "Design: Portable, Low Noise (≈63–68 dB), 100% Copper Coil",
    ],
  },
  {
    id: 13,
    name: "Elepaq 3.5KVA Petrol Generator (Manual Start)",
    image: genproduct.gen3,
    images: [genproduct.gen3, genproduct.gen3b, genproduct.gen3c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Power Output: 3.5KVA (≈ 3000W running capacity)",
      "Fuel Type: Petrol (Gasoline Engine)",
      "Starting System: Manual (Recoil Start)",
      "Engine Type: 4-Stroke, Single Cylinder, Air-Cooled (OHV)",
      "Voltage: 220V / 50Hz (Single Phase)",
      "Fuel Tank Capacity: 15 Litres",
      "Noise Level: ≈ 63dB (Low Noise Design)",
    ],
  },
  {
    id: 14,
    name: "Elepaq 4.5KVA Manual Start Petrol Generator",
    image: genproduct.gen4,
    images: [genproduct.gen4, genproduct.gen4b, genproduct.gen4c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Power Output: 4.5KVA (≈ 4000W running capacity)",
      "Fuel Type: Petrol (Gasoline Engine)",
      "Starting System: Manual (Recoil Pull Start)",
      "Engine Type: 4-Stroke, Single Cylinder, Air-Cooled (OHV)",
      "Coil Type: 100% Copper (High efficiency & durability)",
      "Fuel Tank Capacity: ~15 Litres",
      "Voltage: 220V / 50Hz (Single Phase)",
    ],
  },
  {
    id: 15,
    name: "Elepaq 4.5KVA Key Start Petrol Generator",
    image: genproduct.gen5,
    images: [genproduct.gen5, genproduct.gen5b, genproduct.gen5c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Power Output: 4.5KVA (≈ 4.0–4.2KVA running capacity)",
      "Starting System: Key Start (Electric) + Manual Backup",
      "Engine Type: 4-Stroke, Single Cylinder, Air-Cooled (OHV)",
      "Coil Type: 100% Copper (High efficiency & durability)",
      "Fuel Type: Petrol (Gasoline Engine)",
      "Fuel Tank Capacity: ~15 Litres",
      "Voltage: 220V / 50Hz (Single Phase)",
    ],
  },

  // WASHING MACHINES (16–21)
  {
    id: 16,
    name: "Hisense 5KG Twin Tub Washing Machine",
    image: washproduct.wash1,
    images: [washproduct.wash1, washproduct.wash1b, washproduct.wash1c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 5KG Wash & Spin",
      "Type: Twin Tub (Wash + Spin Dryer)",
      "Loading Type: Top Load",
      "Body Design: Rust-proof Plastic Body",
      "Control: Manual Knobs (User-friendly panel)",
      "Special Features: Lint Filter & Water Selector",
      "Drum: Durable Inner Tub (Efficient washing performance)",
    ],
  },
  {
    id: 17,
    name: "Hisense 7.5KG Twin Tub Washing Machine",
    image: washproduct.wash2,
    images: [washproduct.wash2, washproduct.wash2b, washproduct.wash2c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 7.5KG Wash & Spin",
      "Type: Twin Tub (Wash + Spin Dryer)",
      "Loading Type: Top Load (Semi-Automatic)",
      "Body Design: Rust-proof Plastic Body",
      "Control: Manual Knobs (User-friendly panel)",
      "Special Features: Lint Filter & Water Selector",
      "Design: Classic, Durable Build (Twin Tub System)",
    ],
  },
  {
    id: 18,
    name: "Hisense 11KG Twin Tub Washing Machine",
    image: washproduct.wash3,
    images: [washproduct.wash3, washproduct.wash3b, washproduct.wash3c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 11KG Wash & Spin (Large Family Size)",
      "Type: Twin Tub (Wash + Spin Dryer)",
      "Loading Type: Top Load (Semi-Automatic)",
      "Control: Manual Knobs (Easy operation)",
      "Body Design: Durable Rust-proof Plastic",
      "Special Features: Lint Filter & Water Selector",
      "Function: Wash & Spin simultaneously (Saves time)",
    ],
  },
  {
    id: 19,
    name: "Hisense 8KG Fully Automatic Washing Machine",
    image: washproduct.wash4,
    images: [washproduct.wash4, washproduct.wash4b, washproduct.wash4c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 8KG (Suitable for medium households)",
      "Type: Fully Automatic (Wash & Spin in one tub)",
      "Loading Type: Front Load / Top Load (varies by model)",
      "Control System: Smart Fuzzy Logic (auto water & wash adjustment)",
      "Spin Speed: Up to 700 RPM (smooth & efficient drying)",
      "Special Features: Delay Start, Foam Control, Self-Clean Drum",
      "Design: LED Display, Modern Silver Finish",
    ],
  },
  {
    id: 20,
    name: "Snowsea 8.5KG Twin Tub Manual Washing Machine",
    image: washproduct.wash5,
    images: [washproduct.wash5, washproduct.wash5b, washproduct.wash5c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 8.5KG Wash & Spin (Medium–Large Load)",
      "Type: Twin Tub (Wash + Spin Dryer)",
      "Loading Type: Top Load (Semi-Automatic)",
      "Control: Manual Timer Knobs (Easy to operate)",
      "Body Design: Durable Plastic (Rust-resistant)",
      "Drum: Stainless Steel Inner Tub",
      "Function: Wash & Spin simultaneously (Time-saving)",
    ],
  },
  {
    id: 21,
    name: "Nexus 7KG Fully Automatic Washing Machine",
    image: washproduct.wash6,
    images: [washproduct.wash6, washproduct.wash6b, washproduct.wash6c],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 7 kg (ideal for medium-sized families)",
      "Type: Fully Automatic Front Load (no need to transfer between tubs)",
      "Spin Speed: Up to 1200 RPM (fast drying & less moisture)",
      "Energy Efficient: Designed to save water and electricity",
      "Wash Programs: Multiple cycles including hot wash, pre-wash & eco wash",
      "Convenience Features: Auto restart, child lock & LED display panel",
      "Durable Build: Tough glass door & anti-rust body",
    ],
  },

  // FRIDGES & FREEZERS (22–36)
  {
    id: 22,
    name: "Royal 105L Single Door Refrigerator",
    image: fridgeproduct.fridge1,
    images: [
      fridgeproduct.fridge1,
      fridgeproduct.fridge1b,
      fridgeproduct.fridge1c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 105 Litres (Compact size for small homes/offices)",
      "Type: Single Door (Direct Cool Technology)",
      "Cooling System: Fast & Even Cooling (Direct Cool)",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Compact, modern with adjustable shelves",
      "Special Features: Interior light, egg tray & vegetable box",
      "Extra: Lock system & adjustable thermostat",
    ],
  },
  {
    id: 23,
    name: "Hisense 90L",
    image: fridgeproduct.fridge2,
    images: [
      fridgeproduct.fridge2,
      fridgeproduct.fridge2b,
      fridgeproduct.fridge2c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 90 Litres (Compact size for small homes/offices)",
      "Type: Single Door (Direct Cool Technology)",
      "Cooling System: Fast & Efficient Cooling (Direct Cool)",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Compact, modern with durable shelves",
      "Special Features: Interior light, door compartments & freezer box",
      "Extra: Adjustable thermostat & low noise operation",
    ],
  },
  {
    id: 24,
    name: "Hisense 124L Double door",
    image: fridgeproduct.fridge3,
    images: [
      fridgeproduct.fridge3,
      fridgeproduct.fridge3b,
      fridgeproduct.fridge3c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 124 Litres (Ideal for small to medium households)",
      "Type: Double Door (Separate fridge & freezer compartments)",
      "Cooling System: Fast & Even Cooling (Direct Cool)",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Modern finish with spacious interior & adjustable shelves",
      "Special Features: Interior light, vegetable box & door compartments",
      "Extra: Adjustable thermostat & low noise operation",
    ],
  },
  {
    id: 25,
    name: "Hisense 150L single door",
    image: fridgeproduct.fridge4,
    images: [
      fridgeproduct.fridge4,
      fridgeproduct.fridge4b,
      fridgeproduct.fridge4c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 150 Litres (Suitable for small to medium households)",
      "Type: Single Door (Direct Cool Technology)",
      "Cooling System: Fast & Efficient Cooling (Direct Cool)",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Sleek, modern with spacious interior & adjustable shelves",
      "Special Features: Interior light, vegetable box & door compartments",
      "Extra: Adjustable thermostat & low noise operation",
    ],
  },
  {
    id: 26,
    name: "Hisense 145L CHest freezer",
    image: fridgeproduct.fridge5,
    images: [
      fridgeproduct.fridge5,
      fridgeproduct.fridge5b,
      fridgeproduct.fridge5c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 145 Litres (Ideal for home and small business use)",
      "Type: Chest Freezer (Top Opening Design)",
      "Cooling System: Fast Freezing & Long Cooling Retention",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Durable body with spacious storage basket",
      "Special Features: Interior light, removable wire basket & easy drain",
      "Extra: Adjustable thermostat & lock system",
    ],
  },
  {
    id: 27,
    name: "Hisense 200L chest freezer",
    image: fridgeproduct.fridge6,
    images: [
      fridgeproduct.fridge6,
      fridgeproduct.fridge6b,
      fridgeproduct.fridge6c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 200 Litres (Ideal for home and commercial use)",
      "Type: Chest Freezer (Top Opening Design)",
      "Cooling System: Fast Freezing & Long Cooling Retention",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Strong, durable body with spacious interior",
      "Special Features: Interior light, removable storage basket & easy drain",
      "Extra: Adjustable thermostat & lock system",
    ],
  },
  {
    id: 28,
    name: "Hisense 250L chest freezer",
    image: fridgeproduct.fridge7,
    images: [
      fridgeproduct.fridge7,
      fridgeproduct.fridge7b,
      fridgeproduct.fridge7c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 250 Litres (Perfect for large households and commercial use)",
      "Type: Chest Freezer (Top Opening Design)",
      "Cooling System: Fast Freezing & Long Cooling Retention",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Strong, durable body with extra spacious interior",
      "Special Features: Interior light, multiple storage baskets & easy drain",
      "Extra: Adjustable thermostat & lock system",
    ],
  },
  {
    id: 29,
    name: "Skyrun 145L",
    image: fridgeproduct.fridge8,
    images: [
      fridgeproduct.fridge8,
      fridgeproduct.fridge8b,
      fridgeproduct.fridge8c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 145 Litres (Ideal for home and small business use)",
      "Type: Chest Freezer (Top Opening Design)",
      "Cooling System: Fast Freezing & Long Cooling Retention",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Durable anti-rust body with spacious interior",
      "Special Features: Interior LED light, storage basket & power indicator",
      "Extra: Safety lock, front drainage & adjustable thermostat",
    ],
  },
  {
    id: 30,
    name: "Skyrun 155L",
    image: fridgeproduct.fridge9,
    images: [
      fridgeproduct.fridge9,
      fridgeproduct.fridge9b,
      fridgeproduct.fridge9c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 155 Litres (Ideal for home and small business use)",
      "Type: Chest Freezer (Top Opening Design)",
      "Cooling System: Fast Freezing & Long Cooling Retention",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Durable anti-rust body with spacious interior",
      "Special Features: Interior LED light, storage basket & power indicator",
      "Extra: Safety lock, front drainage & adjustable thermostat",
    ],
  },
  {
    id: 31,
    name: "Skyrun 200L",
    image: fridgeproduct.fridge10,
    images: [
      fridgeproduct.fridge10,
      fridgeproduct.fridge10b,
      fridgeproduct.fridge10c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 200 Litres (Ideal for medium-sized families and commercial use)",
      "Type: Chest Freezer (Top Opening Design)",
      "Cooling System: Fast Freezing & Long Cooling Retention",
      "Energy Efficiency: Low power consumption & energy saving",
      "Design: Durable anti-rust body with spacious interior",
      "Special Features: Interior LED light, storage basket & power indicator",
      "Extra: Safety lock, front drainage & adjustable thermostat",
    ],
  },
  {
    id: 32,
    name: "Nexus 200l",
    image: fridgeproduct.fridge11,
    images: [
      fridgeproduct.fridge11,
      fridgeproduct.fridge11b,
      fridgeproduct.fridge11c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 200 Litres (Ideal for medium-sized households and businesses)",
      "Type: Chest Freezer (Top Opening Design)",
      "Cooling System: Fast Freezing Function & High-Efficiency Compressor",
      "Energy Efficiency: Energy Saving A+ (Low power consumption)",
      "Design: Durable anti-rust body with easy-to-clean interior",
      "Special Features: LED door lamp, removable storage basket & power indicator",
      "Extra: Lock and key, adjustable thermostat & 100% HFC/FCKW free",
    ],
  },
  {
    id: 33,
    name: "Aeon 200L",
    image: fridgeproduct.fridge12,
    images: [
      fridgeproduct.fridge12,
      fridgeproduct.fridge12b,
      fridgeproduct.fridge12c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 200 Litres (Ideal for home and retail use)",
      "Type: Chest Freezer (Top Opening Design)",
      "Cooling System: Instant Flash Freezing & Thermal Insulation",
      "Energy Efficiency: Low noise and energy-saving technology",
      "Design: Sleek anti-rust body with embossed aluminum interior",
      "Special Features: Interior light, heavy-duty storage basket & power pilot light",
      "Extra: Key lock system, easy-access drainage & multi-range thermostat",
    ],
  },
  {
    id: 34,
    name: "Thermocool 130L freezer",
    image: fridgeproduct.fridge13,
    images: [
      fridgeproduct.fridge13,
      fridgeproduct.fridge13b,
      fridgeproduct.fridge13c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 130 Litres (Ideal for small families and compact spaces)",
      "Type: Chest Freezer (Top Opening Design)",
      "Cooling System: Super Fast Freezing & 100-Hour Cooling Retention",
      "Energy Efficiency: High-efficiency compressor & energy saving technology",
      "Design: Durable anti-rust body with zinc-coated interior",
      "Special Features: Interior LED light, storage basket & power indicator",
      "Extra: Safety lock with keys, front drainage & adjustable thermostat",
    ],
  },
  {
    id: 35,
    name: "Thermocool 185L double door",
    image: fridgeproduct.fridge14,
    images: [
      fridgeproduct.fridge14,
      fridgeproduct.fridge14b,
      fridgeproduct.fridge14c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 5KG Wash & Spin",
      "Type: Twin Tub (Wash + Spin Dryer)",
      "Loading Type: Top Load",
      "Body Design: Rust-proof Plastic Body",
      "Control: Manual Knobs (User-friendly panel)",
      "Special Features: Lint Filter & Water Selector",
      "Drum: Durable Inner Tub (Efficient washing performance)",
    ],
  },
  {
    id: 36,
    name: "Snowsea 190l",
    image: fridgeproduct.fridge15,
    images: [
      fridgeproduct.fridge15,
      fridgeproduct.fridge15b,
      fridgeproduct.fridge15c,
    ],
    price: "₦400,000",
    oldPrice: "₦430,000",
    features: [
      "Capacity: 190 Litres (Ideal for home and small business use)",
      "Type: Chest Freezer (Top Opening Design)",
      "Cooling System: Fast Freezing & Extra-Cold Cooling Retention",
      "Energy Efficiency: Low energy consumption & cost-effective operation",
      "Design: High-quality anti-rust body with spacious interior",
      "Special Features: Interior LED light, storage basket & power indicator",
      "Extra: Safety lock, front drainage & adjustable thermostat control",
    ],
  },
];
